AllCops:
  Exclude:
    - vendor/**/*

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

MethodLength:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - Rakefile
    - metadata.rb
